### ISSUE TITLE
License

### ISSUE THREAD

**Issue by igeligel** [3YOURMIND/3YDMoeller#1]
Let us choose a license for this project. I would recommend:

- MIT
- Apache 2.0

Please tell me if you have other opinions (i think those licenses are the most open ones)

**Comment by Louis-Simon22** [comment]
Hey guys, I would like to use this code as well and would require a license. Would it be possible to include one? The code this is inspired from is MIT too, but its some very old C.

Thank you

**Comment by Tradias** [comment]
Addressed by https://github.com/3YOURMIND/3YDMoeller/pull/2

**Comment by Louis-Simon22** [comment]
Thank you very much
